[2022-07-13 07:19:22,361] INFO [Worker clientId=connect-1, groupId=connect-cluster] Group coordinator kafka:29092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response.isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:913)
[2022-07-13 07:19:22,398] INFO [Worker clientId=connect-1, groupId=connect-cluster] Discovered group coordinator kafka:29092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:850)
[2022-07-13 07:19:22,403] INFO [Worker clientId=connect-1, groupId=connect-cluster] Discovered group coordinator kafka:29092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:850)
[2022-07-13 07:19:22,408] INFO [Worker clientId=connect-1, groupId=connect-cluster] Group coordinator kafka:29092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable.isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:913)
[2022-07-13 07:19:22,516] INFO [Worker clientId=connect-1, groupId=connect-cluster] Discovered group coordinator kafka:29092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:850)
[2022-07-13 07:19:22,524] INFO [Worker clientId=connect-1, groupId=connect-cluster] Member connect-1-9831a13f-1e24-4c5d-8926-9f6c3fb194c9 sending LeaveGroup request to coordinator kafka:29092 (id: 2147483647 rack: null) due to consumer poll timeout has expired. This means the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time processing messages. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:1045)
[2022-07-13 07:19:22,528] INFO [Worker clientId=connect-1, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:221)
[2022-07-13 07:19:22,532] INFO [Worker clientId=connect-1, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:540)
[2022-07-13 07:19:22,551] INFO [Worker clientId=connect-1, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:540)
[2022-07-13 07:19:22,568] INFO [Worker clientId=connect-1, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=5, memberId='connect-1-a533cc20-84ea-426e-b672-dadc4e6f2283', protocol='sessioned'} (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:596)
[2022-07-13 07:19:22,583] INFO [Worker clientId=connect-1, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=5, memberId='connect-1-a533cc20-84ea-426e-b672-dadc4e6f2283', protocol='sessioned'} (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:760)
[2022-07-13 07:19:22,588] INFO [Worker clientId=connect-1, groupId=connect-cluster] Joined group at generation 5 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-1-a533cc20-84ea-426e-b672-dadc4e6f2283', leaderUrl='http://kconnect:8083/', offset=4, connectorIds=[], taskIds=[], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1699)
[2022-07-13 07:19:22,595] INFO [Worker clientId=connect-1, groupId=connect-cluster] Starting connectors and tasks using config offset 4 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1244)
[2022-07-13 07:19:22,602] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1272)
[2022-07-13 07:19:22,635] INFO [Consumer clientId=consumer-connect-cluster-3, groupId=connect-cluster] Error sending fetch request (sessionId=568654795, epoch=402) to node 0: (org.apache.kafka.clients.FetchSessionHandler:481)
org.apache.kafka.common.errors.DisconnectException
[2022-07-13 07:19:22,744] INFO [Worker clientId=connect-1, groupId=connect-cluster] Session key updated (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1587)
[2022-07-13 07:33:23,337] INFO [Worker clientId=connect-1, groupId=connect-cluster] Group coordinator kafka:29092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: session timed out without receiving a heartbeat response.isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:913)
[2022-07-13 07:33:23,355] INFO [Worker clientId=connect-1, groupId=connect-cluster] Discovered group coordinator kafka:29092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:850)
[2022-07-13 07:33:23,360] INFO [Worker clientId=connect-1, groupId=connect-cluster] Discovered group coordinator kafka:29092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:850)
[2022-07-13 07:33:23,365] INFO [Worker clientId=connect-1, groupId=connect-cluster] Group coordinator kafka:29092 (id: 2147483647 rack: null) is unavailable or invalid due to cause: coordinator unavailable.isDisconnected: false. Rediscovery will be attempted. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:913)
[2022-07-13 07:33:23,474] INFO [Worker clientId=connect-1, groupId=connect-cluster] Discovered group coordinator kafka:29092 (id: 2147483647 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:850)
[2022-07-13 07:33:23,599] INFO [Consumer clientId=consumer-connect-cluster-2, groupId=connect-cluster] Error sending fetch request (sessionId=670776688, epoch=14669) to node 0: (org.apache.kafka.clients.FetchSessionHandler:481)
org.apache.kafka.common.errors.DisconnectException
[2022-07-13 07:33:23,636] INFO [Consumer clientId=consumer-connect-cluster-1, groupId=connect-cluster] Error sending fetch request (sessionId=1809637535, epoch=14658) to node 0: (org.apache.kafka.clients.FetchSessionHandler:481)
org.apache.kafka.common.errors.DisconnectException
